'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Available languages
export type Language = 'tr' | 'en';

// Context type
type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
};

// Create the context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: 'tr',
  setLanguage: () => {},
  t: () => '',
});

// Translations object
const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Common
    'save': 'Kaydet',
    'cancel': 'İptal',
    'delete': 'Sil',
    'change': 'Değiştir',
    'upload': 'Yükle',
    'logout': 'Çıkış',
    'success': 'Başarılı',
    'error': 'Hata',
    'loading': 'Yükleniyor',
    'yes': 'Evet',
    'no': 'Hayır',
    'copy': 'Kopyala',
    'copied': 'Kopyalandı',
    'homepage': 'Ana Sayfa',
    'addPhoto': 'Fotoğraf Ekle',
    'photoAdd': 'Fotoğraf Ekle',
    'photoUrl': 'Fotoğraf URL\'si girin',
    'addViaUrl': 'URL ile Ekle',
    'addFromComputer': 'Bilgisayarınızdan Seçin',
    'cropAndSave': 'Kırp ve Kaydet',
    'crop': 'Kırp',
    'or': 'veya',
    'add': 'Ekle',
    'yourCoins': 'Coinleriniz',
    
    // Navbar
    'navbar.home': 'Ana Sayfa',
    'navbar.matches': 'Eşleşmeler',
    'navbar.messages': 'Mesajlar',
    'navbar.membership': 'Üyelik',
    'navbar.gifts': 'Hediyelerim',
    'navbar.profile': 'Profil',
    'navbar.whoLikedMe': 'Beğenenler',
    'navbar.admin': 'Admin',
    'navbar.notifications': 'Bildirimler',
    'navbar.noNotifications': 'Yeni bildiriminiz yok',
    'navbar.newMatches': '{count} yeni eşleşme',
    'navbar.unreadMessages': '{count} okunmamış mesaj',
    'navbar.viewMessage': 'Mesaj #{index} - Görüntüle',
    'navbar.newMessage': 'Yeni mesaj #{index} - Görüntüle',
    'navbar.logout': 'Çıkış',
    
    // Gifts Page
    'gifts.title': 'Hediyelerim',
    'gifts.coins': 'Coin',
    'gifts.buyCoins': '+ Coin Al',
    'gifts.close': 'Kapat',
    'gifts.loading': 'Hediyeler yükleniyor...',
    'gifts.fetchError': 'Hediyeler getirilemedi',
    'gifts.loadError': 'Hediyeler yüklenirken bir hata oluştu',
    'gifts.processingError': 'Hediye işlenirken bir hata oluştu',
    'gifts.sentYou': 'Size {giftName} gönderdi',
    'gifts.silverGift': 'Gümüş Hediye',
    'gifts.goldGift': 'Altın Hediye',
    'gifts.emeraldGift': 'Zümrüt Hediye',
    'gifts.diamondGift': 'Elmas Hediye',
    'gifts.rubyGift': 'Yakut Hediye',
    'gifts.special': 'Özel',
    'gifts.premium': 'Premium',
    'gifts.diamondDescription': 'Karşı tarafa numaranızı iletir',
    'gifts.rubyDescription': 'Karşı tarafa numaranızı ve bir özel mesajınızı iletir',
    'gifts.phone': 'Telefon',
    'gifts.noPhoneShared': 'Telefon numarası paylaşılmamış',
    'gifts.processing': 'İşleniyor...',
    'gifts.accept': 'Kabul Et',
    'gifts.reject': 'Reddet',
    'gifts.accepted': 'Bu hediyeyi kabul ettiniz',
    'gifts.rejected': 'Bu hediyeyi reddettiniz',
    'gifts.specialMessage': 'Özel Mesaj',
    'gifts.noGiftsYet': 'Henüz hediyeniz yok',
    'gifts.noGiftsDescription': 'Hiç hediye almadınız. Birileri size hediye gönderdiğinde burada görünecek.',
    'gifts.returnHome': 'Ana Sayfaya Dön',
    
    // Ana Sayfa
    'homepage.about': 'Hakkında:',
    'homepage.readMore': 'Devamını Oku',
    'homepage.readLess': 'Daha Az Göster',
    'homepage.gender': 'Cinsiyet',
    'homepage.female': 'Kadın',
    'homepage.male': 'Erkek',
    'homepage.other': 'Diğer',
    'homepage.interests': 'İlgi Alanları',
    'homepage.lookingFor': 'Aradığı',
    'homepage.longTermRelationship': 'Uzun Süreli İlişki Arıyor',
    'homepage.shortTermRelationship': 'Kısa Süreli İlişki Arıyor',
    'homepage.friendship': 'Arkadaşlık Arıyor',
    'homepage.oneNightStand': 'Tek Gecelik İlişki Arıyor',
    'homepage.sendGift': 'Hediye Gönder',
    'homepage.sendMessage': 'Mesaj Gönder',
    'homepage.like': 'Beğen',
    'homepage.skip': 'Atla',
    'homepage.congrats': 'Tebrikler! Herkesi Değerlendirdiniz',
    'homepage.noMoreProfiles': 'Şu an için gösterilebilecek başka kullanıcı kalmadı. Daha sonra gelin veya yöneliminizi değiştirin.',
    'homepage.tryAgain': 'Tekrar Dene',
    'homepage.goToMatches': 'Eşleşmelerime Git',
    'homepage.somethingWentWrong': 'Bir Şeyler Ters Gitti',
    'homepage.report': 'Bildir',
    'homepage.reportProfile': 'Profili Bildir',
    'homepage.reportReason': 'Bildirim nedeni',
    'homepage.submitReport': 'Bildirimi Gönder',
    'homepage.cancel': 'İptal',
    'homepage.reportReasonPlaceholder': 'Bu profili neden bildirdiğinizi açıklayın...',
    'homepage.reportSuccess': 'Bildiriminiz için teşekkürler. Raporunuz incelenecektir.',
    'homepage.continue': 'Devam Et',
    'homepage.noOneAvailable': 'Şu An Kimse Yok',
    'homepage.checkLater': 'Daha sonra tekrar kontrol edebilirsiniz veya profilinizi güncelleyebilirsiniz.',
    'homepage.editProfile': 'Profili Düzenle',
    'homepage.foundMatch': 'Eşleşme Buldunuz!',
    'homepage.youAndMatched': 'Siz ve {name} birbirinizi beğendiniz! Şimdi mesajlaşmaya başlayabilirsiniz.',
    'homepage.selectGiftFor': '{name} için bir hediye seç',
    
    // Profile Compatibility
    'profile.compatibility': 'Yalnızca tüm bilgileri eksiksiz girilmiş kullanıcılar eşleşme sisteminden faydalanabilir.',
    'profile.compatibilityStatus': 'Sizin uygunluk durumunuz:',
    'profile.compatible': 'Uygun',
    'profile.incompatible': 'Uygun Değil',
    'profile.missingItems': 'Eksik alanlar:',
    'profile.missingIntroduction': 'Kendinizi tanıtın bölümünü doldurun',
    'profile.missingGender': 'Cinsiyetinizi seçin',
    'profile.missingInterests': 'İlgi alanlarınızı belirtin',
    'profile.missingReason': 'Neden burada olduğunuzu seçin',
    'profile.missingPhotos': 'En az bir fotoğraf ekleyin',
    'profile.missingAvatar': 'Profil fotoğrafı ekleyin',
    
    // Referral Code
    'referral.yourReferralCode': 'Referans Kodunuz',
    'referral.description': 'Bu kodu daha önce uygulamaya kayıt olmamış bir arkadaşınıza verin, arkadaşınız tarayıcı üzerinden finder.rina-social.com adresinden sizin referans kodunuzu girerek profil oluştursun ve aşağıdaki ödülleri kazanın:',
    'referral.friendReward': 'Arkadaşınız için: 1000 coin',
    'referral.yourReward': 'Size: 2 günlük GOLD üyelik',
    
    // Photo Upload
    'photo.upload': 'Fotoğraf Yükle',
    'photo.uploadAvatar': 'Avatar Yükle',
    'photo.cropAvatar': 'Avatar Kırp',
    'photo.cropPhoto': 'Fotoğraf Kırp',
    'photo.selectImage': 'Resim Seç',
    'photo.selectedPhotoNumber': 'Fotoğraf',
    'photo.goldOnly': 'GOLD Özel',
    'photo.platinumOnly': 'PLATINUM Özel',
    'photo.upgradeGold': 'Gold üye olun!',
    'photo.upgradePlatinum': 'Platinum üye olun!',
    
    // Profile Edit Page
    'profileEdit.title': 'Profili Düzenle',
    'profileEdit.basicInfo': 'Temel Bilgiler',
    'profileEdit.name': 'İsim',
    'profileEdit.age': 'Yaş',
    'profileEdit.phone': 'Telefon',
    'profileEdit.membershipStatus': 'Üyelik Durumu',
    'profileEdit.standardMember': 'STANDART ÜYE',
    'profileEdit.goldMember': 'GOLD ÜYE',
    'profileEdit.platinumMember': 'PLATINUM ÜYE',
    'profileEdit.standardMemberDesc': 'Sadece ilk 3 fotoğraf slotunu kullanabilirsiniz.',
    'profileEdit.goldMemberDesc': '5 fotoğraf slotunu kullanabilir ve daha fazla özelliğe sahipsiniz!',
    'profileEdit.platinumMemberDesc': 'Tüm fotoğraf slotlarını kullanabilir ve en özel özelliklere sahipsiniz!',
    'profileEdit.remainingTime': 'Kalan süre',
    'profileEdit.referralCode': 'Referans Kodunuz',
    'profileEdit.referralDesc': 'Bu kodu daha önce uygulamaya kayıt olmamış bir arkadaşınıza verin, arkadaşınız tarayıcı üzerinden finder.rina-social.com adresinden sizin referans kodunuzu girerek profil oluştursun ve aşağıdaki ödülleri kazanın:',
    'profileEdit.referralFriendReward': 'Arkadaşınız için: 1000 coin',
    'profileEdit.referralYourReward': 'Size: 2 günlük GOLD üyelik',
    'profileEdit.avatar': 'Profil Resmi',
    'profileEdit.uploadAvatar': 'Avatar Yükle',
    'profileEdit.removeAvatar': 'Avatar\'ı kaldır',
    'profileEdit.aboutYou': 'Kendinizi Tanıtın',
    'profileEdit.aboutYouPlaceholder': 'Kendiniz hakkında en az 100 karakter yazın...',
    'profileEdit.charactersCount': 'Karakter sayısı',
    'profileEdit.minCharsRequired': 'Minimum 100 karakter gerekli',
    'profileEdit.gender': 'Cinsiyet',
    'profileEdit.female': 'Kadın',
    'profileEdit.male': 'Erkek',
    'profileEdit.other': 'Diğer',
    'profileEdit.orientation': 'Yönelim Seçimi',
    'profileEdit.goldMembersOnly': '(Gold Üyelere Özel)',
    'profileEdit.platinumMultipleOrientation': 'Platinum Çoklu Yönelim Seçimi',
    'profileEdit.visibleTo': 'Kişiler için görüneceksiniz',
    'profileEdit.noSelectionYet': 'Henüz seçim yapılmadı',
    'profileEdit.orientationGoldInfo': 'Yönelim seçimi Gold ve Platinum Üyelere özel bir özelliktir. Gold üye olduğunuzda sadece seçtiğiniz cinsiyetteki kişileri görürsünüz.',
    'profileEdit.orientationPlatinumInfo': 'Platinum Üyeliğe yükseltirseniz çoklu yönelim seçimi yapabilirsiniz!',
    'profileEdit.interests': 'Nelerden Hoşlanırsınız?',
    'profileEdit.interestsPlaceholder': 'İlgi alanlarınızı, hobilerinizi ve sevdiğiniz şeyleri yazın...',
    'profileEdit.reason': 'Neden Buradasınız?',
    'profileEdit.reasonSelect': 'Seçiniz',
    'profileEdit.reasonFriendship': 'Arkadaş Edinmek',
    'profileEdit.reasonOneNight': 'Tek Gecelik Eğlence',
    'profileEdit.reasonShortTerm': 'Kısa Süreli İlişki',
    'profileEdit.reasonLongTerm': 'Uzun Süreli İlişki',
    'profileEdit.photos': 'Fotoğraflar',
    'profileEdit.maxPhotosStandard': '(Maksimum 3 adet)',
    'profileEdit.maxPhotosGold': '(Maksimum 5 adet)',
    'profileEdit.maxPhotosPlatinum': '(Maksimum 6 adet)',
    'profileEdit.photoSlotGoldWarning': 'Bu slot sadece GOLD ve PLATINUM üyeler için kullanılabilir!',
    'profileEdit.photoSlotPlatinumWarning': 'Bu slot sadece PLATINUM üyeler için kullanılabilir!',
    'profileEdit.saveProfile': 'Profili Kaydet',
    'profileEdit.profileUpdated': 'Profiliniz başarıyla güncellendi',
    'profileEdit.minSelfIntroError': 'Kendinizi tanıtırken en az 100 karakter kullanmalısınız',
    'profileEdit.orientationGoldError': 'Yönelim seçeneği Gold üyelere özel bir özelliktir',
    'profileEdit.languageSettings': 'Dil Ayarları',
    'profileEdit.turkish': 'Türkçe',
    'profileEdit.english': 'English',
    
    // Gift Panel
    'gift.sendGift': 'Hediye Gönder',
    'gift.selectGiftFor': '{name} için bir hediye seç',
    'gift.silver': 'Gümüş',
    'gift.gold': 'Altın',
    'gift.emerald': 'Zümrüt',
    'gift.diamond': 'Elmas',
    'gift.ruby': 'Yakut',
    'gift.sendingGift': 'Gönderiliyor...',
    'gift.sendGiftWithPrice': '{giftName} Hediyesini Gönder ({price} Coin)',
    'gift.specialMessage': 'Özel mesajınız (zorunlu)...',
    'gift.phoneNumber': 'Karşı tarafa numaranızı iletir',
    'gift.phoneAndMessage': 'Karşı tarafa numaranızı ve bir özel mesajınızı iletir',
    'gift.errorRequiredMessage': 'Yakut hediyesi için özel mesaj girmelisiniz.',
    'gift.successMessage': '{giftName} başarıyla gönderildi!',
    'gift.feeExplanation': '* Her hediye gönderiminde 500 coin beğenme ücreti + hediye ücreti alınır.',
    'gift.transferExplanation': '* Hediye alan kullanıcıya hediye değeri kadar coin transfer edilir.',
    'gift.autoLikeExplanation': '* Hediye gönderdiğiniz kullanıcıyı otomatik olarak beğenmiş olursunuz.',
    'gift.diamondExplanation': '* Elmas hediyesi karşı tarafa telefon numaranızı iletir.',
    'gift.rubyExplanation': '* Yakut hediyesi karşı tarafa telefon numaranızı ve özel mesajınızı iletir.',
    'gift.cancel': 'İptal',
    
    // Matches Page
    'matches.title': 'Eşleşmeleriniz',
    'matches.loading': 'Yükleniyor',
    'matches.error': 'Hata',
    'matches.tryAgain': 'Tekrar Dene',
    'matches.noMatches': 'Henüz Eşleşmeniz Yok',
    'matches.noMatchesDescription': 'Eşleşme bulmak için ana sayfada diğer kullanıcıları beğenmeye başlayın.',
    'matches.returnToHome': 'Ana Sayfaya Dön',
    'matches.matchedOn': 'Eşleşme:',
    'matches.messageButtonAriaLabel': 'Mesaj gönder',
    
    // Messages Page
    'messages.title': 'Mesajlar',
    'messages.noMessages': 'Henüz Bir Mesajınız Yok',
    'messages.noMessagesDescription': 'Eşleşmelerinizle sohbet etmeye başlayın!',
    'messages.goToMatches': 'Eşleşmelere Git',
    'messages.yesterday': 'Dün',
    'messages.sunday': 'Pazar',
    'messages.monday': 'Pazartesi',
    'messages.tuesday': 'Salı',
    'messages.wednesday': 'Çarşamba',
    'messages.thursday': 'Perşembe',
    'messages.friday': 'Cuma',
    'messages.saturday': 'Cumartesi',
    'messages.error': 'Konuşmalar yüklenirken bir hata oluştu',
    'messages.serverError': 'Sunucu hatası. Lütfen daha sonra tekrar deneyin.',
    'messages.newMatch': 'Yeni eşleşme',
    'messages.unknownUser': 'Bilinmeyen Kullanıcı',
    
    // Message Detail Page
    'messageDetail.goldMember': 'Gold Üye',
    'messageDetail.messageRequest': 'Mesaj İsteği',
    'messageDetail.requestMessage': '{name} size mesaj göndermek istiyor. Kabul ediyor musunuz?',
    'messageDetail.accept': 'Kabul Et',
    'messageDetail.reject': 'Reddet',
    'messageDetail.unauthorized': 'Yetkisiz Erişim',
    'messageDetail.noAccess': 'Bu konuşmaya erişim yetkiniz bulunmuyor.',
    'messageDetail.acceptToChat': 'Mesajlaşmaya başlamak için isteği kabul edin.',
    'messageDetail.waitingForApproval': 'Onay Bekleniyor',
    'messageDetail.waitingMessage': '{name} mesaj isteğinizi onaylayana kadar bekleyin.',
    'messageDetail.startChat': 'Sohbete Başla',
    'messageDetail.noMessages': 'Bu eşleşmeyle henüz bir mesaj yok. İlk mesajı gönderip sohbeti başlatabilirsin!',
    'messageDetail.today': 'Bugün',
    'messageDetail.warning': '⚠️ UYARI! ⚠️',
    'messageDetail.backToMessages': 'Mesajlara Geri Dön',
    'messageDetail.ok': 'Tamam',
    'messageDetail.photoSent': '📷 Görsel gönderildi',
    'messageDetail.addPhotoCaption': 'Görsel ile ilgili bir mesaj ekleyin (isteğe bağlı)',
    'messageDetail.writeMessage': 'Mesajınızı yazın...',
    'messageDetail.imagePreview': 'Medya önizleme',
    
    // Membership Page
    'membership.title': 'Üyelik Bilgileri',
    'membership.backToHome': 'Ana Sayfa',
    'membership.accountInfo': 'Hesap Bilgileri',
    'membership.membershipType': 'Üyelik Tipi',
    'membership.standardMember': 'STANDART',
    'membership.goldMember': 'GOLD',
    'membership.platinumMember': 'PLATINUM',
    'membership.remainingTime': 'Kalan süre',
    'membership.unlimitedMembership': 'Süresiz Üyelik',
    'membership.continuingMembership': '{type} üyeliğiniz devam ediyor',
    'membership.platinumTime': 'Platinum Üyelik Süresi',
    'membership.goldTime': 'Gold Üyelik Süresi',
    'membership.balance': 'Bakiye',
    'membership.adding': 'Ekleniyor...',
    'membership.coins': 'Coinler',
    'membership.addCoins': 'Coin Ekle',
    'membership.upgradeToPlatinum': 'Platinum\'a Yükselt',
    'membership.getBuyGold': 'Gold Üyelik Al',
    'membership.getBuyPlatinum': 'Platinum Üyelik Al',
    'membership.goldAdvantages': 'Gold Üyelik Avantajları',
    'membership.orientationSelection': 'Yönelim seçimi',
    'membership.orientationDetail': 'İstediğiniz cinsiyetle eşleşin!',
    'membership.photoSlots': '5 fotoğraf slotu',
    'membership.photoSlotsDetail': 'Profil sayfanızda daha fazla fotoğraf gösterin!',
    'membership.priorityDisplay': 'Öncelikli gösterim',
    'membership.priorityDisplayDetail': 'Profiliniz diğer kullanıcılara daha sık gösterilir!',
    'membership.specialBadge': 'Özel rozet',
    'membership.specialBadgeDetail': 'Profilinizde parıldayan gold rozetiyle öne çıkın!',
    'membership.messagePriority': 'Mesajlarda öncelik',
    'membership.messagePriorityDetail': 'Mesajlar sayfasında standart kullanıcıların üstünde gözükün!',
    'membership.extraGifts': 'Ek hediyeler',
    'membership.extraGiftsDetail': 'Özel günlerde ekstra hediye ve bonuslar!',
    'membership.getGoldNow': 'Şimdi Gold Üye olun ve tüm bu ayrıcalıklardan yararlanın!',
    'membership.buyGoldMembership': 'GOLD ÜYELİK SATIN AL',
    'membership.platinumAdvantages': 'Platinum Üyelik Avantajları',
    'membership.multiOrientation': 'Çoklu yönelim seçme',
    'membership.multiOrientationDetail': 'Birden fazla cinsiyet tercihi yapabilirsiniz!',
    'membership.topMessages': 'Mesajlarda en üstte',
    'membership.topMessagesDetail': 'Mesaj sayfasında her zaman en üstte gözükün!',
    'membership.whoLikedMe': 'Beni beğenenler',
    'membership.whoLikedMeDetail': 'Sizi beğenen kullanıcıları görün ve eşleşin!',
    'membership.tenPhotoSlots': '10 fotoğraf slotu',
    'membership.tenPhotoSlotsDetail': 'Daha fazla fotoğraf yükleyebilirsiniz!',
    'membership.premiumLook': 'Premium görünüm',
    'membership.premiumLookDetail': 'Özel animasyonlar ve görsel efektler!',
    'membership.getPlatinumNow': 'Platinum Üye olun ve tüm premium ayrıcalıklara sahip olun!',
    'membership.buyPlatinumMembership': 'PLATINUM ÜYELİK SATIN AL',
    
    // Purchase Page
    'purchase.title': 'Satın Alım',
    'purchase.backToMembership': 'Üyelik Sayfasına Dön',
    'purchase.purchaseOperations': 'Satın Alım İşlemleri',
    'purchase.buyCoins': 'Coin Satın Al',
    'purchase.buyGold': 'Gold Üyelik Al',
    'purchase.buyPlatinum': 'Platinum Üyelik Al',
    'purchase.coinPurchase': 'Coin Satın Alma',
    'purchase.enterCoinAmount': 'İstediğiniz Coin Miktarını Girin',
    'purchase.coinPlaceholder': 'Örn: 100, 250, 1000',
    'purchase.unitPrice': 'Birim fiyat:',
    'purchase.perCoin': '/ coin',
    'purchase.total': 'Toplam:',
    'purchase.buyWithBalance': 'Bakiye ile {amount} Coin Satın Al',
    'purchase.processing': 'İşleniyor...',
    'purchase.insufficientBalance': 'Yetersiz bakiye',
    'purchase.goldPurchase': 'Gold Üyelik Satın Alma',
    'purchase.selectMembershipDuration': 'Üyelik Süresi Seçin',
    'purchase.day': 'Gün',
    'purchase.buyGoldWithBalance': 'Bakiye ile {duration} Günlük Gold Üyelik Satın Al',
    'purchase.goldBenefits': 'Gold Üyelik Avantajları:',
    'purchase.orientationChoice': 'Yönelim seçimi - İstediğiniz cinsiyetle eşleşin!',
    'purchase.morePhotos': '5 fotoğraf slotu - Daha fazla fotoğraf gösterin!',
    'purchase.unlimitedLikes': 'Sınırsız beğeni - Günlük beğeni limitiniz sınırsız olur!',
    'purchase.priorityShowing': 'Öncelikli gösterim - Profiliniz daha sık gösterilir!',
    'purchase.andMore': 'Ve çok daha fazlası...',
    'purchase.platinumPurchase': 'Platinum Üyelik Satın Alma',
    'purchase.buyPlatinumWithBalance': 'Bakiye ile {duration} Günlük Platinum Üyelik Satın Al',
    'purchase.platinumBenefits': 'Platinum Üyelik Avantajları:',
    'purchase.multipleOrientations': 'Çoklu yönelim seçimi - Birden fazla cinsiyetle eşleşin!',
    'purchase.tenPhotos': '10 fotoğraf slotu - Daha fazla fotoğraf gösterin!',
    'purchase.vipDisplay': 'VIP gösterim - Profiliniz en üstte gösterilir!',
    'purchase.premiumSupport': 'Premium destek - Öncelikli müşteri desteği!',
    'purchase.allGoldFeatures': 'Gold üyelik avantajlarının tümü ve daha fazlası!',
    'purchase.failpurchase': 'Yetersiz bakiye',
    
    // Admin Page
    'admin.title': 'Admin Paneli',
    'admin.moderatorTitle': 'Moderatör Paneli',
    'admin.loading': 'Yükleniyor...',
    'admin.unauthorized': 'Yetkisiz erişim',
    'admin.users': 'Kullanıcılar',
    'admin.matches': 'Eşleşmeler',
    'admin.gifts': 'Hediyeler',
    'admin.giftManagement': 'Hediye Yönetimi',
    'admin.giftManagementDesc': 'Sistem hediyelerini yönetin',
    'admin.announcementManagement': 'Duyuru Yönetimi',
    'admin.announcementDesc': 'Sistem duyurularını yönetin',
    'admin.matchesManagement': 'Eşleşmeler',
    'admin.matchesManagementDesc': 'Kullanıcı eşleşmelerini yönetin',
    'admin.giftHistory': 'Hediye Geçmişi',
    'admin.giftHistoryDesc': 'Gönderilen hediyeleri görüntüle',
    'admin.membershipPrices': 'Üyelik Fiyatları',
    'admin.membershipPricesDesc': 'Üyelik ve coin fiyatlarını düzenle',
    'admin.userManagement': 'Kullanıcı Yönetimi',
    'admin.userManagementDesc': 'Kullanıcıları düzenle, banla veya yasakla',
    'admin.systemSettings': 'Sistem Ayarları',
    'admin.systemSettingsDesc': 'Genel sistem ayarlarını yapılandır',
    'admin.reports': 'Raporlar',
    'admin.reportsDesc': 'Kullanıcı şikayetlerini incele ve yönet',
    'admin.adminLogs': 'Admin Logları',
    'admin.adminLogsDesc': 'Admin işlemlerini ve değişikliklerini görüntüle',
    'admin.edit': 'Düzenle',
    'admin.view': 'Görüntüle',
    'admin.manage': 'Yönet',
    'admin.configure': 'Yapılandır',
    'admin.review': 'İncele',
    
    // Admin Users Page
    'adminUsers.title': 'Kullanıcı Yönetimi',
    'adminUsers.backToAdmin': 'Admin Paneline Dön',
    'adminUsers.loading': 'Yükleniyor...',
    'adminUsers.searchPlaceholder': 'Kullanıcı adı veya ID ile ara...',
    'adminUsers.searching': 'Aranıyor...',
    'adminUsers.search': 'Ara',
    'adminUsers.clear': 'Temizle',
    'adminUsers.user': 'Kullanıcı',
    'adminUsers.membershipType': 'Üyelik Tipi',
    'adminUsers.status': 'Durum',
    'adminUsers.banInfo': 'Ban Bilgisi',
    'adminUsers.actions': 'İşlemler',
    'adminUsers.admin': '(Admin)',
    'adminUsers.age': '{age} yaşında',
    'adminUsers.platinum': 'Platinum',
    'adminUsers.gold': 'Gold',
    'adminUsers.standard': 'Standart',
    'adminUsers.banned': 'Banlı',
    'adminUsers.active': 'Aktif',
    'adminUsers.unspecified': 'Belirtilmemiş',
    'adminUsers.untilDate': '{date} tarihine kadar',
    'adminUsers.view': 'Görüntüle',
    'adminUsers.unban': 'Ban Kaldır',
    'adminUsers.ban': 'Banla',
    'adminUsers.loadingUsers': 'Kullanıcılar yükleniyor...',
    'adminUsers.searchingUsers': 'Kullanıcılar aranıyor...',
    'adminUsers.noUsersFound': 'Hiçbir kullanıcı bulunamadı',
    'adminUsers.totalUsers': 'Toplam {count} kullanıcı',
    'adminUsers.previous': 'Önceki',
    'adminUsers.next': 'Sonraki',
    'adminUsers.banUser': 'Kullanıcıyı Banla - {username}',
    'adminUsers.banDuration': 'Ban Süresi',
    'adminUsers.permanent': 'Süresiz (Kalıcı)',
    'adminUsers.day1': '1 gün',
    'adminUsers.day3': '3 gün',
    'adminUsers.day7': '7 gün',
    'adminUsers.day14': '14 gün',
    'adminUsers.day30': '30 gün',
    'adminUsers.day90': '90 gün',
    'adminUsers.banReason': 'Ban Nedeni',
    'adminUsers.banReasonPlaceholder': 'Kullanıcının yasaklanma nedenini girin...',
    'adminUsers.cancel': 'İptal',
    'adminUsers.processing': 'İşleniyor...',
    'adminUsers.banUserButton': 'Kullanıcıyı Banla',
    'adminUsers.userBanned': 'Kullanıcı {duration} banlandı',
    'adminUsers.userBannedPermanently': 'Kullanıcı kalıcı olarak banlandı',
    'adminUsers.banError': 'Kullanıcı banlanırken bir hata oluştu',
    'adminUsers.userUnbanned': 'Kullanıcı banı kaldırıldı',
    'adminUsers.unbanError': 'Kullanıcı banı kaldırılırken bir hata oluştu',
    'adminUsers.unauthorized': 'Admin yetkisi bulunamadı. Ana sayfaya yönlendiriliyorsunuz.',
    'adminUsers.fetchError': 'Kullanıcılar getirilirken bir hata oluştu',
    'adminUsers.searchError': 'Kullanıcılar aranırken bir hata oluştu',
    
    // Admin User Detail Page
    'adminUserDetail.title': 'Kullanıcı Detayları',
    'adminUserDetail.backToUsers': 'Kullanıcı Listesine Dön',
    'adminUserDetail.edit': 'Düzenle',
    'adminUserDetail.loading': 'Yükleniyor...',
    'adminUserDetail.userNotFound': 'Kullanıcı bulunamadı',
    'adminUserDetail.profilePictureUrl': 'Profil Resmi URL',
    'adminUserDetail.membershipType': 'Üyelik Tipi',
    'adminUserDetail.standard': 'Standart',
    'adminUserDetail.gold': 'Gold',
    'adminUserDetail.platinum': 'Platinum',
    'adminUserDetail.coinAmount': 'Coin Miktarı',
    'adminUserDetail.adminPermission': 'Admin Yetkisi',
    'adminUserDetail.platinumMember': 'Platinum Üye',
    'adminUserDetail.goldMember': 'Gold Üye',
    'adminUserDetail.standardMember': 'Standart Üye',
    'adminUserDetail.coins': 'Coin',
    'adminUserDetail.admin': 'Admin',
    'adminUserDetail.banned': 'Banlı',
    'adminUserDetail.username': 'Kullanıcı Adı',
    'adminUserDetail.age': 'Yaş',
    'adminUserDetail.gender': 'Cinsiyet',
    'adminUserDetail.female': 'Kadın',
    'adminUserDetail.male': 'Erkek',
    'adminUserDetail.other': 'Diğer',
    'adminUserDetail.interestedGender': 'İlgilendiği Cinsiyet',
    'adminUserDetail.all': 'Hepsi',
    'adminUserDetail.phone': 'Telefon',
    'adminUserDetail.about': 'Hakkında',
    'adminUserDetail.interests': 'İlgi Alanları',
    'adminUserDetail.reason': 'Arama Nedeni',
    'adminUserDetail.longTermRelationship': 'Uzun Süreli İlişki',
    'adminUserDetail.shortTermRelationship': 'Kısa Süreli İlişki',
    'adminUserDetail.friendship': 'Arkadaşlık',
    'adminUserDetail.oneNightStand': 'Tek Gecelik İlişki',
    'adminUserDetail.banStatus': 'Ban Durumu',
    'adminUserDetail.banReason': 'Neden',
    'adminUserDetail.banExpiry': 'Ban Bitiş',
    'adminUserDetail.cancel': 'İptal',
    'adminUserDetail.saveChanges': 'Değişiklikleri Kaydet',
    'adminUserDetail.saving': 'Kaydediliyor...',
    'adminUserDetail.userStats': 'Kullanıcı İstatistikleri',
    'adminUserDetail.matches': 'Eşleşme',
    'adminUserDetail.likes': 'Beğeni',
    'adminUserDetail.sentGifts': 'Gönderilen Hediye',
    'adminUserDetail.receivedGifts': 'Alınan Hediye',
    'adminUserDetail.photos': 'Fotoğraflar',
    'adminUserDetail.remove': 'Kaldır',
    'adminUserDetail.confirmPhotoDelete': 'Bu fotoğrafı silmek istediğinize emin misiniz?',
    'adminUserDetail.photoDeleted': 'Fotoğraf başarıyla silindi',
    'adminUserDetail.photoDeletedMock': 'Fotoğraf başarıyla silindi (mock işlem)',
    'adminUserDetail.photoDeleteError': 'Fotoğraf silinirken bir hata oluştu: Backend API hazır değil.',
    'adminUserDetail.avatarManagement': 'Avatar Yönetimi',
    'adminUserDetail.removeAvatar': 'Avatarı Kaldır',
    'adminUserDetail.confirmAvatarDelete': 'Kullanıcının avatarını kaldırmak istediğinize emin misiniz?',
    'adminUserDetail.avatarRemoved': 'Avatar başarıyla kaldırıldı',
    'adminUserDetail.avatarRemovedMock': 'Avatar başarıyla kaldırıldı (mock işlem)',
    'adminUserDetail.avatarRemoveError': 'Avatar kaldırılırken bir hata oluştu: Backend API hazır değil.',
    'adminUserDetail.adminCheckError': 'Admin doğrulama hatası: Ana sayfaya yönlendiriliyorsunuz.',
    'adminUserDetail.userFetchError': 'Kullanıcı bilgileri getirilemedi',
    'adminUserDetail.profileUpdateSuccess': 'Kullanıcı profili başarıyla güncellendi',
    'adminUserDetail.profileUpdateError': 'Kullanıcı profili güncellenirken bir hata oluştu. Backend API hazır değil.',
    'adminUserDetail.membershipChangeWarning': 'Dikkat: Üyelik tipini değiştirdiğinizde, kullanıcının {currentCount} fotoğrafından {deleteCount} tanesi otomatik olarak silinecektir. Değişikliği kaydettiğinizde, sadece ilk {newLimit} fotoğraf korunacaktır.',
    
    // Admin Reports Page
    'adminReports.title': 'Kullanıcı Raporları',
    'adminReports.pending': 'Beklemede',
    'adminReports.approved': 'Onaylandı',
    'adminReports.rejected': 'Reddedildi',
    'adminReports.fetchError': 'Raporlar alınamadı',
    'adminReports.noReports': 'Rapor Bulunamadı',
    'adminReports.noReportsForStatus': 'Seçilen durum için rapor bulunmamaktadır.',
    'adminReports.reportNumber': 'Rapor No',
    'adminReports.reporter': 'Raporlayan',
    'adminReports.reportedUser': 'Raporlanan',
    'adminReports.reason': 'Sebep',
    'adminReports.date': 'Tarih',
    'adminReports.status': 'Durum',
    'adminReports.actions': 'İşlemler',
    'adminReports.bannedUser': 'Banlı Kullanıcı',
    'adminReports.review': 'İncele',
    'adminReports.totalReports': 'Toplam {count} rapor bulundu',
    'adminReports.previous': 'Önceki',
    'adminReports.next': 'Sonraki',
    
    // Admin Report Detail Page
    'adminReportDetail.backToReports': 'Geri Dön',
    'adminReportDetail.reportNumber': 'Rapor',
    'adminReportDetail.fetchError': 'Rapor detayları alınamadı',
    'adminReportDetail.processError': 'Rapor işlenemedi',
    'adminReportDetail.processSuccess': 'Rapor başarıyla işlendi!',
    'adminReportDetail.reportInfo': 'Rapor Bilgileri',
    'adminReportDetail.reportReason': 'Rapor Sebebi',
    'adminReportDetail.reportDate': 'Rapor Tarihi',
    'adminReportDetail.reviewNote': 'İnceleme Notu',
    'adminReportDetail.noNote': 'Not bulunmuyor',
    'adminReportDetail.rewardGiven': 'Verilen Ödül',
    'adminReportDetail.reportingUser': 'Raporlayan Kullanıcı',
    'adminReportDetail.userId': 'Kullanıcı ID',
    'adminReportDetail.viewUserProfile': 'Kullanıcı Profilini Görüntüle',
    'adminReportDetail.reportedUser': 'Raporlanan Kullanıcı',
    'adminReportDetail.viewProfile': 'Profili Görüntüle',
    'adminReportDetail.banUser': 'Banla',
    'adminReportDetail.dontBan': 'Banlama',
    'adminReportDetail.reportProcess': 'Rapor İşlemi',
    'adminReportDetail.approve': 'Onayla',
    'adminReportDetail.reject': 'Reddet',
    'adminReportDetail.reviewNotePlaceholder': 'İnceleme notunuzu buraya yazın...',
    'adminReportDetail.banUserCheckbox': 'Kullanıcıyı banla',
    'adminReportDetail.rewardReporter': 'Raporlayan kullanıcıya ödül ver',
    'adminReportDetail.rewardAmount': 'Ödül Miktarı (Coin)',
    'adminReportDetail.processing': 'İşleniyor...',
    'adminReportDetail.processReport': 'Raporu İşle',
    'adminReportDetail.reportNotFound': 'Rapor Bulunamadı',
    'adminReportDetail.reportNotFoundDesc': 'İstenen rapor bulunamadı veya erişim izniniz yok.',
    // Admin Announcement
    'admin.announcement.pageTitle': 'Duyuru Yönetimi',
    'admin.announcement.htmlHelp': 'HTML Yardımı',
    'admin.announcement.htmlTags': 'HTML Etiketleri',
    'admin.announcement.htmlHelpDesc': 'Duyuru içeriğinde HTML etiketleri kullanabilirsiniz. Etiket eklemek için yukarıdaki butonları kullanın.',
    'admin.announcement.image': 'Görsel',
    'admin.announcement.bold': 'Kalın',
    'admin.announcement.italic': 'İtalik',
    'admin.announcement.list': 'Liste',
    'admin.announcement.link': 'Link',
    'admin.announcement.editTitle': 'Duyuru Düzenle',
    'admin.announcement.addTitle': 'Yeni Duyuru Ekle',
    'admin.announcement.titleLabel': 'Başlık',
    'admin.announcement.titlePlaceholder': 'Duyuru başlığı',
    'admin.announcement.contentLabel': 'İçerik',
    'admin.announcement.contentPlaceholder': 'Duyuru içeriği (HTML desteklenir)',
    'admin.announcement.updateButton': 'Güncelle',
    'admin.announcement.addButton': 'Ekle',
    'admin.announcement.cancelButton': 'İptal',
    'admin.announcement.processing': 'İşleniyor...',
    'admin.announcement.currentAnnouncements': 'Mevcut Duyurular',
    'admin.announcement.loading': 'Yükleniyor...',
    'admin.announcement.noAnnouncements': 'Henüz duyuru bulunmuyor.',
    'admin.announcement.slot': 'Slot',
    'admin.announcement.editAction': 'Düzenle',
    'admin.announcement.deleteAction': 'Sil',
    'admin.announcement.status': 'Durum',
    'admin.announcement.active': 'Aktif',
    'admin.announcement.passive': 'Pasif',
    'admin.announcement.deleteConfirm': 'Bu duyuruyu silmek istediğinize emin misiniz?',
    // Messages Page

    'messageDetail.searchEmojis': 'Emoji ara...',
    'messageDetail.loadMore': 'Daha Fazla Mesaj Yükle',
    'messageDetail.loading': 'Yükleniyor...',
    'messageDetail.isTyping': 'yazıyor...',
  },
  en: {
    // Common
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'change': 'Change',
    'upload': 'Upload',
    'logout': 'Logout',
    'success': 'Success',
    'error': 'Error',
    'loading': 'Loading',
    'yes': 'Yes',
    'no': 'No',
    'copy': 'Copy',
    'copied': 'Copied',
    'homepage': 'Home',
    'addPhoto': 'Add Photo',
    'photoAdd': 'Add Photo',
    'photoUrl': 'Enter photo URL',
    'addViaUrl': 'Add via URL',
    'addFromComputer': 'Select from computer',
    'cropAndSave': 'Crop and Save',
    'crop': 'Crop',
    'or': 'or',
    'add': 'Add',
    'yourCoins': 'Your Coins',
    
    // Navbar
    'navbar.home': 'Home',
    'navbar.matches': 'Matches',
    'navbar.messages': 'Messages',
    'navbar.membership': 'Membership',
    'navbar.gifts': 'My Gifts',
    'navbar.profile': 'Profile',
    'navbar.whoLikedMe': 'Who Liked Me',
    'navbar.admin': 'Admin',
    'navbar.notifications': 'Notifications',
    'navbar.noNotifications': 'No new notifications',
    'navbar.newMatches': '{count} new matches',
    'navbar.unreadMessages': '{count} unread messages',
    'navbar.viewMessage': 'Message #{index} - View',
    'navbar.newMessage': 'New message #{index} - View',
    'navbar.logout': 'Logout',
    
    // Gifts Page
    'gifts.title': 'My Gifts',
    'gifts.coins': 'Coins',
    'gifts.buyCoins': '+ Buy Coins',
    'gifts.close': 'Close',
    'gifts.loading': 'Loading gifts...',
    'gifts.fetchError': 'Could not retrieve gifts',
    'gifts.loadError': 'An error occurred while loading gifts',
    'gifts.processingError': 'An error occurred while processing the gift',
    'gifts.sentYou': 'Sent you {giftName}',
    'gifts.silverGift': 'Silver Gift',
    'gifts.goldGift': 'Gold Gift',
    'gifts.emeraldGift': 'Emerald Gift',
    'gifts.diamondGift': 'Diamond Gift',
    'gifts.rubyGift': 'Ruby Gift',
    'gifts.special': 'Special',
    'gifts.premium': 'Premium',
    'gifts.diamondDescription': 'Shares your phone number with the recipient',
    'gifts.rubyDescription': 'Shares your phone number and a special message with the recipient',
    'gifts.phone': 'Phone',
    'gifts.noPhoneShared': 'No phone number shared',
    'gifts.processing': 'Processing...',
    'gifts.accept': 'Accept',
    'gifts.reject': 'Reject',
    'gifts.accepted': 'You have accepted this gift',
    'gifts.rejected': 'You have rejected this gift',
    'gifts.specialMessage': 'Special Message',
    'gifts.noGiftsYet': 'No gifts yet',
    'gifts.noGiftsDescription': 'You haven\'t received any gifts. When someone sends you a gift, it will appear here.',
    'gifts.returnHome': 'Return to Home',
    
    // Ana Sayfa
    'homepage.about': 'About:',
    'homepage.readMore': 'Read More',
    'homepage.readLess': 'Read Less',
    'homepage.gender': 'Gender',
    'homepage.female': 'Female',
    'homepage.male': 'Male',
    'homepage.other': 'Other',
    'homepage.interests': 'Interests',
    'homepage.lookingFor': 'Looking For',
    'homepage.longTermRelationship': 'Looking for Long Term Relationship',
    'homepage.shortTermRelationship': 'Looking for Short Term Relationship',
    'homepage.friendship': 'Looking for Friendship',
    'homepage.oneNightStand': 'Looking for One Night Stand',
    'homepage.sendGift': 'Send Gift',
    'homepage.sendMessage': 'Send Message',
    'homepage.like': 'Like',
    'homepage.skip': 'Skip',
    'homepage.congrats': 'Congratulations! You\'ve Reviewed Everyone',
    'homepage.noMoreProfiles': 'There are no more users to show at the moment. Come back later or change your orientation.',
    'homepage.tryAgain': 'Try Again',
    'homepage.goToMatches': 'Go to My Matches',
    'homepage.somethingWentWrong': 'Something Went Wrong',
    'homepage.report': 'Report',
    'homepage.reportProfile': 'Report Profile',
    'homepage.reportReason': 'Reason for report',
    'homepage.submitReport': 'Submit Report',
    'homepage.cancel': 'Cancel',
    'homepage.reportReasonPlaceholder': 'Explain why you are reporting this profile...',
    'homepage.reportSuccess': 'Thank you for your report. We will review it.',
    'homepage.continue': 'Continue',
    'homepage.noOneAvailable': 'No One Available',
    'homepage.checkLater': 'You can check back later or update your profile.',
    'homepage.editProfile': 'Edit Profile',
    'homepage.foundMatch': 'You Found a Match!',
    'homepage.youAndMatched': 'You and {name} liked each other! You can now start messaging.',
    'homepage.selectGiftFor': 'Select a gift for {name}',
    
    // Profile Compatibility
    'profile.compatibility': 'Only users with complete profiles can benefit from the matching system.',
    'profile.compatibilityStatus': 'Your compatibility status:',
    'profile.compatible': 'Compatible',
    'profile.incompatible': 'Incompatible',
    'profile.missingItems': 'Missing items:',
    'profile.missingIntroduction': 'Fill in the about you section',
    'profile.missingGender': 'Select your gender',
    'profile.missingInterests': 'Specify your interests',
    'profile.missingReason': 'Select why you are here',
    'profile.missingPhotos': 'Add at least one photo',
    'profile.missingAvatar': 'Add a profile picture',
    
    // Referral Code
    'referral.yourReferralCode': 'Your Referral Code',
    'referral.description': 'Give this code to a friend who hasn\'t registered before, let them create a profile through finder.rina-social.com with your referral code and earn the following rewards:',
    'referral.friendReward': 'For your friend: 1000 coins',
    'referral.yourReward': 'For you: 2 days of GOLD membership',
    
    // Photo Upload
    'photo.upload': 'Upload Photo',
    'photo.uploadAvatar': 'Upload Avatar',
    'photo.cropAvatar': 'Crop Avatar',
    'photo.cropPhoto': 'Crop Photo',
    'photo.selectImage': 'Select Image',
    'photo.selectedPhotoNumber': 'Photo',
    'photo.goldOnly': 'GOLD Only',
    'photo.platinumOnly': 'PLATINUM Only',
    'photo.upgradeGold': 'Upgrade to Gold!',
    'photo.upgradePlatinum': 'Upgrade to Platinum!',
    
    // Profile Edit Page
    'profileEdit.title': 'Edit Profile',
    'profileEdit.basicInfo': 'Basic Information',
    'profileEdit.name': 'Name',
    'profileEdit.age': 'Age',
    'profileEdit.phone': 'Phone',
    'profileEdit.membershipStatus': 'Membership Status',
    'profileEdit.standardMember': 'STANDARD MEMBER',
    'profileEdit.goldMember': 'GOLD MEMBER',
    'profileEdit.platinumMember': 'PLATINUM MEMBER',
    'profileEdit.standardMemberDesc': 'You can use only the first 3 photo slots.',
    'profileEdit.goldMemberDesc': 'You can use 5 photo slots and access more features!',
    'profileEdit.platinumMemberDesc': 'You can use all photo slots and access exclusive features!',
    'profileEdit.remainingTime': 'Remaining time',
    'profileEdit.referralCode': 'Your Referral Code',
    'profileEdit.referralDesc': 'Give this code to a friend who hasn\'t registered before, let them create a profile through finder.rina-social.com with your referral code and earn the following rewards:',
    'profileEdit.referralFriendReward': 'For your friend: 1000 coins',
    'profileEdit.referralYourReward': 'For you: 2 days of GOLD membership',
    'profileEdit.avatar': 'Profile Picture',
    'profileEdit.uploadAvatar': 'Upload Avatar',
    'profileEdit.removeAvatar': 'Remove Avatar',
    'profileEdit.aboutYou': 'About You',
    'profileEdit.aboutYouPlaceholder': 'Write at least 100 characters about yourself...',
    'profileEdit.charactersCount': 'Character count',
    'profileEdit.minCharsRequired': 'Minimum 100 characters required',
    'profileEdit.gender': 'Gender',
    'profileEdit.female': 'Female',
    'profileEdit.male': 'Male',
    'profileEdit.other': 'Other',
    'profileEdit.orientation': 'Orientation Selection',
    'profileEdit.goldMembersOnly': '(Gold Members Only)',
    'profileEdit.platinumMultipleOrientation': 'Platinum Multiple Orientation Selection',
    'profileEdit.visibleTo': 'You will be visible to',
    'profileEdit.noSelectionYet': 'No selection yet',
    'profileEdit.orientationGoldInfo': 'Orientation selection is a feature exclusive to Gold and Platinum Members. As a Gold member, you\'ll only see people of your selected gender.',
    'profileEdit.orientationPlatinumInfo': 'Upgrade to Platinum Membership to select multiple orientations!',
    'profileEdit.interests': 'What Do You Like?',
    'profileEdit.interestsPlaceholder': 'Write your interests, hobbies, and things you enjoy...',
    'profileEdit.reason': 'Why Are You Here?',
    'profileEdit.reasonSelect': 'Select',
    'profileEdit.reasonFriendship': 'Make Friends',
    'profileEdit.reasonOneNight': 'One Night Fun',
    'profileEdit.reasonShortTerm': 'Short Term Relationship',
    'profileEdit.reasonLongTerm': 'Long Term Relationship',
    'profileEdit.photos': 'Photos',
    'profileEdit.maxPhotosStandard': '(Maximum 3)',
    'profileEdit.maxPhotosGold': '(Maximum 5)',
    'profileEdit.maxPhotosPlatinum': '(Maximum 6)',
    'profileEdit.photoSlotGoldWarning': 'This slot is only available for GOLD and PLATINUM members!',
    'profileEdit.photoSlotPlatinumWarning': 'This slot is only available for PLATINUM members!',
    'profileEdit.saveProfile': 'Save Profile',
    'profileEdit.profileUpdated': 'Your profile has been successfully updated',
    'profileEdit.minSelfIntroError': 'You must use at least 100 characters to introduce yourself',
    'profileEdit.orientationGoldError': 'Orientation selection is a Gold members-only feature',
    'profileEdit.languageSettings': 'Language Settings',
    'profileEdit.turkish': 'Turkish',
    'profileEdit.english': 'English',
    
    // Gift Panel
    'gift.sendGift': 'Send Gift',
    'gift.selectGiftFor': 'Select a gift for {name}',
    'gift.silver': 'Silver',
    'gift.gold': 'Gold',
    'gift.emerald': 'Emerald',
    'gift.diamond': 'Diamond',
    'gift.ruby': 'Ruby',
    'gift.sendingGift': 'Sending...',
    'gift.sendGiftWithPrice': 'Send {giftName} Gift ({price} Coins)',
    'gift.specialMessage': 'Your special message (required)...',
    'gift.phoneNumber': 'Shares your phone number with the recipient',
    'gift.phoneAndMessage': 'Shares your phone number and a special message with the recipient',
    'gift.errorRequiredMessage': 'You must enter a special message for the Ruby gift.',
    'gift.successMessage': '{giftName} sent successfully!',
    'gift.feeExplanation': '* Each gift sending incurs a 500 coin like fee + gift cost.',
    'gift.transferExplanation': '* The recipient receives coins equal to the gift value.',
    'gift.autoLikeExplanation': '* You automatically like the user when you send them a gift.',
    'gift.diamondExplanation': '* Diamond gift shares your phone number with the recipient.',
    'gift.rubyExplanation': '* Ruby gift shares your phone number and special message with the recipient.',
    'gift.cancel': 'Cancel',
    
    // Matches Page
    'matches.title': 'Your Matches',
    'matches.loading': 'Loading',
    'matches.error': 'Error',
    'matches.tryAgain': 'Try Again',
    'matches.noMatches': 'No Matches Yet',
    'matches.noMatchesDescription': 'Start liking other users on the homepage to find matches.',
    'matches.returnToHome': 'Return to Homepage',
    'matches.matchedOn': 'Matched:',
    'matches.messageButtonAriaLabel': 'Send message',
    
    // Messages Page
    'messages.title': 'Messages',
    'messages.noMessages': 'No Messages Yet',
    'messages.noMessagesDescription': 'Start chatting with your matches!',
    'messages.goToMatches': 'Go to Matches',
    'messages.yesterday': 'Yesterday',
    'messages.sunday': 'Sunday',
    'messages.monday': 'Monday',
    'messages.tuesday': 'Tuesday',
    'messages.wednesday': 'Wednesday',
    'messages.thursday': 'Thursday',
    'messages.friday': 'Friday',
    'messages.saturday': 'Saturday',
    'messages.error': 'An error occurred while loading conversations',
    'messages.serverError': 'Server error. Please try again later.',
    'messages.newMatch': 'New match',
    'messages.unknownUser': 'Unknown user',
    
    // Message Detail Page
    'messageDetail.goldMember': 'Gold Member',
    'messageDetail.messageRequest': 'Message Request',
    'messageDetail.requestMessage': '{name} wants to send you a message. Do you accept?',
    'messageDetail.accept': 'Accept',
    'messageDetail.reject': 'Reject',
    'messageDetail.unauthorized': 'Unauthorized Access',
    'messageDetail.noAccess': 'You do not have access to this conversation.',
    'messageDetail.acceptToChat': 'Accept the request to start messaging.',
    'messageDetail.waitingForApproval': 'Waiting for Approval',
    'messageDetail.waitingMessage': 'Wait until {name} approves your message request.',
    'messageDetail.startChat': 'Start a Chat',
    'messageDetail.noMessages': 'No messages yet. Send the first message to start chatting!',
    'messageDetail.today': 'Today',
    'messageDetail.warning': '⚠️ WARNING! ⚠️',
    'messageDetail.backToMessages': 'Back to Messages',
    'messageDetail.ok': 'OK',
    'messageDetail.photoSent': '📷 Photo sent',
    'messageDetail.addPhotoCaption': 'Add a message about the image (optional)',
    'messageDetail.writeMessage': 'Write your message...',
    'messageDetail.imagePreview': 'Image preview',
    
    // Membership Page
    'membership.title': 'Membership Information',
    'membership.backToHome': 'Home',
    'membership.accountInfo': 'Account Information',
    'membership.membershipType': 'Membership Type',
    'membership.standardMember': 'STANDARD',
    'membership.goldMember': 'GOLD',
    'membership.platinumMember': 'PLATINUM',
    'membership.remainingTime': 'Remaining time',
    'membership.unlimitedMembership': 'Unlimited Membership',
    'membership.continuingMembership': 'Your {type} membership is continuing',
    'membership.platinumTime': 'Platinum Membership Time',
    'membership.goldTime': 'Gold Membership Time',
    'membership.balance': 'Balance',
    'membership.adding': 'Adding...',
    'membership.coins': 'Coins',
    'membership.addCoins': 'Add Coins',
    'membership.upgradeToPlatinum': 'Upgrade to Platinum',
    'membership.getBuyGold': 'Get Gold Membership',
    'membership.getBuyPlatinum': 'Get Platinum Membership',
    'membership.goldAdvantages': 'Gold Membership Benefits',
    'membership.orientationSelection': 'Orientation selection',
    'membership.orientationDetail': 'Match with your preferred gender!',
    'membership.photoSlots': '5 photo slots',
    'membership.photoSlotsDetail': 'Show more photos on your profile page!',
    'membership.priorityDisplay': 'Priority display',
    'membership.priorityDisplayDetail': 'Your profile is shown more frequently to other users!',
    'membership.specialBadge': 'Special badge',
    'membership.specialBadgeDetail': 'Stand out with a shining gold badge on your profile!',
    'membership.messagePriority': 'Message priority',
    'membership.messagePriorityDetail': 'Appear above standard users in the messages page!',
    'membership.extraGifts': 'Extra gifts',
    'membership.extraGiftsDetail': 'Extra gifts and bonuses on special days!',
    'membership.getGoldNow': 'Become a Gold Member now and enjoy all these privileges!',
    'membership.buyGoldMembership': 'BUY GOLD MEMBERSHIP',
    'membership.platinumAdvantages': 'Platinum Membership Benefits',
    'membership.multiOrientation': 'Multiple orientation selection',
    'membership.multiOrientationDetail': 'You can select multiple gender preferences!',
    'membership.topMessages': 'Top position in messages',
    'membership.topMessagesDetail': 'Always appear at the top of the message page!',
    'membership.whoLikedMe': 'Who liked me',
    'membership.whoLikedMeDetail': 'See users who liked you and match with them!',
    'membership.tenPhotoSlots': '10 photo slots',
    'membership.tenPhotoSlotsDetail': 'You can upload more photos!',
    'membership.premiumLook': 'Premium look',
    'membership.premiumLookDetail': 'Special animations and visual effects!',
    'membership.getPlatinumNow': 'Become a Platinum Member and get all premium privileges!',
    'membership.buyPlatinumMembership': 'BUY PLATINUM MEMBERSHIP',
    
    
    // Purchase Page
    'purchase.title': 'Purchase',
    'purchase.backToMembership': 'Return to Membership Page',
    'purchase.purchaseOperations': 'Purchase Operations',
    'purchase.buyCoins': 'Buy Coins',
    'purchase.buyGold': 'Buy Gold Membership',
    'purchase.buyPlatinum': 'Buy Platinum Membership',
    'purchase.coinPurchase': 'Coin Purchase',
    'purchase.enterCoinAmount': 'Enter Your Desired Coin Amount',
    'purchase.coinPlaceholder': 'Ex: 100, 250, 1000',
    'purchase.unitPrice': 'Unit price:',
    'purchase.perCoin': '/ coin',
    'purchase.total': 'Total:',
    'purchase.buyWithBalance': 'Buy {amount} Coins with Balance',
    'purchase.processing': 'Processing...',
    'purchase.insufficientBalance': 'Insufficient balance',
    'purchase.goldPurchase': 'Gold Membership Purchase',
    'purchase.selectMembershipDuration': 'Select Membership Duration',
    'purchase.day': 'Day',
    'purchase.buyGoldWithBalance': 'Buy {duration}-Day Gold Membership with Balance',
    'purchase.goldBenefits': 'Gold Membership Benefits:',
    'purchase.orientationChoice': 'Orientation selection - Match with your preferred gender!',
    'purchase.morePhotos': '5 photo slots - Show more photos!',
    'purchase.unlimitedLikes': 'Unlimited likes - Your daily like limit becomes unlimited!',
    'purchase.priorityShowing': 'Priority display - Your profile is shown more frequently!',
    'purchase.andMore': 'And much more...',
    'purchase.platinumPurchase': 'Platinum Membership Purchase',
    'purchase.buyPlatinumWithBalance': 'Buy {duration}-Day Platinum Membership with Balance',
    'purchase.platinumBenefits': 'Platinum Membership Benefits:',
    'purchase.multipleOrientations': 'Multiple orientation selection - Match with multiple genders!',
    'purchase.tenPhotos': '10 photo slots - Show more photos!',
    'purchase.vipDisplay': 'VIP display - Your profile is shown at the top!',
    'purchase.premiumSupport': 'Premium support - Priority customer support!',
    'purchase.allGoldFeatures': 'All Gold membership benefits and more!',
    'membership.failpurchase': 'Insufficient funds',
    
    // Admin Page
    'admin.title': 'Admin Panel',
    'admin.moderatorTitle': 'Moderator Panel',
    'admin.loading': 'Loading...',
    'admin.unauthorized': 'Unauthorized access',
    'admin.users': 'Users',
    'admin.matches': 'Matches',
    'admin.gifts': 'Gifts',
    'admin.giftManagement': 'Gift Management',
    'admin.giftManagementDesc': 'Manage system gifts',
    'admin.announcementManagement': 'Announcement Management',
    'admin.announcementDesc': 'Manage system announcements',
    'admin.matchesManagement': 'Matches',
    'admin.matchesManagementDesc': 'Manage user matches',
    'admin.giftHistory': 'Gift History',
    'admin.giftHistoryDesc': 'View sent gifts',
    'admin.membershipPrices': 'Membership Prices',
    'admin.membershipPricesDesc': 'Edit membership and coin prices',
    'admin.userManagement': 'User Management',
    'admin.userManagementDesc': 'Edit, ban or block users',
    'admin.systemSettings': 'System Settings',
    'admin.systemSettingsDesc': 'Configure general system settings',
    'admin.reports': 'Reports',
    'admin.reportsDesc': 'Review and manage user complaints',
    'admin.adminLogs': 'Admin Logs',
    'admin.adminLogsDesc': 'View admin actions and changes',
    'admin.edit': 'Edit',
    'admin.view': 'View',
    'admin.manage': 'Manage',
    'admin.configure': 'Configure',
    'admin.review': 'Review',
    
    // Admin Users Page
    'adminUsers.title': 'User Management',
    'adminUsers.backToAdmin': 'Back to Admin Panel',
    'adminUsers.loading': 'Loading...',
    'adminUsers.searchPlaceholder': 'Search by username or ID...',
    'adminUsers.searching': 'Searching...',
    'adminUsers.search': 'Search',
    'adminUsers.clear': 'Clear',
    'adminUsers.user': 'User',
    'adminUsers.membershipType': 'Membership Type',
    'adminUsers.status': 'Status',
    'adminUsers.banInfo': 'Ban Information',
    'adminUsers.actions': 'Actions',
    'adminUsers.admin': '(Admin)',
    'adminUsers.age': '{age} years old',
    'adminUsers.platinum': 'Platinum',
    'adminUsers.gold': 'Gold',
    'adminUsers.standard': 'Standard',
    'adminUsers.banned': 'Banned',
    'adminUsers.active': 'Active',
    'adminUsers.unspecified': 'Unspecified',
    'adminUsers.untilDate': 'until {date}',
    'adminUsers.view': 'View',
    'adminUsers.unban': 'Unban',
    'adminUsers.ban': 'Ban',
    'adminUsers.loadingUsers': 'Loading users...',
    'adminUsers.searchingUsers': 'Searching users...',
    'adminUsers.noUsersFound': 'No users found',
    'adminUsers.totalUsers': 'Total {count} users',
    'adminUsers.previous': 'Previous',
    'adminUsers.next': 'Next',
    'adminUsers.banUser': 'Ban User - {username}',
    'adminUsers.banDuration': 'Ban Duration',
    'adminUsers.permanent': 'Permanent (Indefinite)',
    'adminUsers.day1': '1 day',
    'adminUsers.day3': '3 days',
    'adminUsers.day7': '7 days',
    'adminUsers.day14': '14 days',
    'adminUsers.day30': '30 days',
    'adminUsers.day90': '90 days',
    'adminUsers.banReason': 'Ban Reason',
    'adminUsers.banReasonPlaceholder': 'Enter the reason for banning this user...',
    'adminUsers.cancel': 'Cancel',
    'adminUsers.processing': 'Processing...',
    'adminUsers.banUserButton': 'Ban User',
    'adminUsers.userBanned': 'User banned for {duration}',
    'adminUsers.userBannedPermanently': 'User permanently banned',
    'adminUsers.banError': 'An error occurred while banning the user',
    'adminUsers.userUnbanned': 'User has been unbanned',
    'adminUsers.unbanError': 'An error occurred while unbanning the user',
    'adminUsers.unauthorized': 'Admin authorization not found. Redirecting to home page.',
    'adminUsers.fetchError': 'An error occurred while fetching users',
    'adminUsers.searchError': 'An error occurred while searching for users',
    
    // Admin User Detail Page
    'adminUserDetail.title': 'User Details',
    'adminUserDetail.backToUsers': 'Back to User List',
    'adminUserDetail.edit': 'Edit',
    'adminUserDetail.loading': 'Loading...',
    'adminUserDetail.userNotFound': 'User not found',
    'adminUserDetail.profilePictureUrl': 'Profile Picture URL',
    'adminUserDetail.membershipType': 'Membership Type',
    'adminUserDetail.standard': 'Standard',
    'adminUserDetail.gold': 'Gold',
    'adminUserDetail.platinum': 'Platinum',
    'adminUserDetail.coinAmount': 'Coin Amount',
    'adminUserDetail.adminPermission': 'Admin Permission',
    'adminUserDetail.platinumMember': 'Platinum Member',
    'adminUserDetail.goldMember': 'Gold Member',
    'adminUserDetail.standardMember': 'Standard Member',
    'adminUserDetail.coins': 'Coins',
    'adminUserDetail.admin': 'Admin',
    'adminUserDetail.banned': 'Banned',
    'adminUserDetail.username': 'Username',
    'adminUserDetail.age': 'Age',
    'adminUserDetail.gender': 'Gender',
    'adminUserDetail.female': 'Female',
    'adminUserDetail.male': 'Male',
    'adminUserDetail.other': 'Other',
    'adminUserDetail.interestedGender': 'Interested Gender',
    'adminUserDetail.all': 'All',
    'adminUserDetail.phone': 'Phone',
    'adminUserDetail.about': 'About',
    'adminUserDetail.interests': 'Interests',
    'adminUserDetail.reason': 'Search Reason',
    'adminUserDetail.longTermRelationship': 'Long Term Relationship',
    'adminUserDetail.shortTermRelationship': 'Short Term Relationship',
    'adminUserDetail.friendship': 'Friendship',
    'adminUserDetail.oneNightStand': 'One Night Stand',
    'adminUserDetail.banStatus': 'Ban Status',
    'adminUserDetail.banReason': 'Reason',
    'adminUserDetail.banExpiry': 'Ban Expiry',
    'adminUserDetail.cancel': 'Cancel',
    'adminUserDetail.saveChanges': 'Save Changes',
    'adminUserDetail.saving': 'Saving...',
    'adminUserDetail.userStats': 'User Statistics',
    'adminUserDetail.matches': 'Matches',
    'adminUserDetail.likes': 'Likes',
    'adminUserDetail.sentGifts': 'Sent Gifts',
    'adminUserDetail.receivedGifts': 'Received Gifts',
    'adminUserDetail.photos': 'Photos',
    'adminUserDetail.remove': 'Remove',
    'adminUserDetail.confirmPhotoDelete': 'Are you sure you want to delete this photo?',
    'adminUserDetail.photoDeleted': 'Photo successfully deleted',
    'adminUserDetail.photoDeletedMock': 'Photo successfully deleted (mock operation)',
    'adminUserDetail.photoDeleteError': 'An error occurred while deleting the photo: Backend API not ready.',
    'adminUserDetail.avatarManagement': 'Avatar Management',
    'adminUserDetail.removeAvatar': 'Remove Avatar',
    'adminUserDetail.confirmAvatarDelete': 'Are you sure you want to remove this user\'s avatar?',
    'adminUserDetail.avatarRemoved': 'Avatar successfully removed',
    'adminUserDetail.avatarRemovedMock': 'Avatar successfully removed (mock operation)',
    'adminUserDetail.avatarRemoveError': 'An error occurred while removing the avatar: Backend API not ready.',
    'adminUserDetail.adminCheckError': 'Admin verification error: Redirecting to home page.',
    'adminUserDetail.userFetchError': 'Could not retrieve user information',
    'adminUserDetail.profileUpdateSuccess': 'User profile successfully updated',
    'adminUserDetail.profileUpdateError': 'An error occurred while updating the user profile. Backend API not ready.',
    'adminUserDetail.membershipChangeWarning': 'Warning: When you change the membership type, {deleteCount} of the user\'s {currentCount} photos will be automatically deleted. When you save the changes, only the first {newLimit} photos will be preserved.',
    
    // Admin Reports Page
    'adminReports.title': 'User Reports',
    'adminReports.pending': 'Pending',
    'adminReports.approved': 'Approved',
    'adminReports.rejected': 'Rejected',
    'adminReports.fetchError': 'Could not retrieve reports',
    'adminReports.noReports': 'No Reports Found',
    'adminReports.noReportsForStatus': 'There are no reports for the selected status.',
    'adminReports.reportNumber': 'Report #',
    'adminReports.reporter': 'Reporter',
    'adminReports.reportedUser': 'Reported User',
    'adminReports.reason': 'Reason',
    'adminReports.date': 'Date',
    'adminReports.status': 'Status',
    'adminReports.actions': 'Actions',
    'adminReports.bannedUser': 'Banned User',
    'adminReports.review': 'Review',
    'adminReports.totalReports': 'Total {count} reports found',
    'adminReports.previous': 'Previous',
    'adminReports.next': 'Next',
    
    // Admin Report Detail Page
    'adminReportDetail.backToReports': 'Go Back',
    'adminReportDetail.reportNumber': 'Report',
    'adminReportDetail.fetchError': 'Could not retrieve report details',
    'adminReportDetail.processError': 'Could not process report',
    'adminReportDetail.processSuccess': 'Report processed successfully!',
    'adminReportDetail.reportInfo': 'Report Information',
    'adminReportDetail.reportReason': 'Report Reason',
    'adminReportDetail.reportDate': 'Report Date',
    'adminReportDetail.reviewNote': 'Review Note',
    'adminReportDetail.noNote': 'No note available',
    'adminReportDetail.rewardGiven': 'Reward Given',
    'adminReportDetail.reportingUser': 'Reporting User',
    'adminReportDetail.userId': 'User ID',
    'adminReportDetail.viewUserProfile': 'View User Profile',
    'adminReportDetail.reportedUser': 'Reported User',
    'adminReportDetail.viewProfile': 'View Profile',
    'adminReportDetail.banUser': 'Ban',
    'adminReportDetail.dontBan': 'Don\'t Ban',
    'adminReportDetail.reportProcess': 'Report Processing',
    'adminReportDetail.approve': 'Approve',
    'adminReportDetail.reject': 'Reject',
    'adminReportDetail.reviewNotePlaceholder': 'Write your review note here...',
    'adminReportDetail.banUserCheckbox': 'Ban this user',
    'adminReportDetail.rewardReporter': 'Give reward to reporting user',
    'adminReportDetail.rewardAmount': 'Reward Amount (Coins)',
    'adminReportDetail.processing': 'Processing...',
    'adminReportDetail.processReport': 'Process Report',
    'adminReportDetail.reportNotFound': 'Report Not Found',
    'adminReportDetail.reportNotFoundDesc': 'The requested report was not found or you do not have access to it.',
    // Admin Announcement
    'admin.announcement.pageTitle': 'Announcement Management',
    'admin.announcement.htmlHelp': 'HTML Help',
    'admin.announcement.htmlTags': 'HTML Tags',
    'admin.announcement.htmlHelpDesc': 'You can use HTML tags in announcement content. Use the buttons above to add tags.',
    'admin.announcement.image': 'Image',
    'admin.announcement.bold': 'Bold',
    'admin.announcement.italic': 'Italic',
    'admin.announcement.list': 'List',
    'admin.announcement.link': 'Link',
    'admin.announcement.editTitle': 'Edit Announcement',
    'admin.announcement.addTitle': 'Add New Announcement',
    'admin.announcement.titleLabel': 'Title',
    'admin.announcement.titlePlaceholder': 'Announcement title',
    'admin.announcement.contentLabel': 'Content',
    'admin.announcement.contentPlaceholder': 'Announcement content (HTML supported)',
    'admin.announcement.updateButton': 'Update',
    'admin.announcement.addButton': 'Add',
    'admin.announcement.cancelButton': 'Cancel',
    'admin.announcement.processing': 'Processing...',
    'admin.announcement.currentAnnouncements': 'Current Announcements',
    'admin.announcement.loading': 'Loading...',
    'admin.announcement.noAnnouncements': 'No announcements yet.',
    'admin.announcement.slot': 'Slot',
    'admin.announcement.editAction': 'Edit',
    'admin.announcement.deleteAction': 'Delete',
    'admin.announcement.status': 'Status',
    'admin.announcement.active': 'Active',
    'admin.announcement.passive': 'Passive',
    'admin.announcement.deleteConfirm': 'Are you sure you want to delete this announcement?',
    // Messages Page

    'messageDetail.searchEmojis': 'Search emojis...',
    'messageDetail.loadMore': 'Load More Messages',
    'messageDetail.loading': 'Loading...',
    'messageDetail.isTyping': 'is typing...',
  }
};

// Language provider component
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // Initialize with Turkish or get from localStorage if available
  const [language, setLanguageState] = useState<Language>('tr');
  
  // Load saved language preference on initial render
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
    }
  }, []);
  
  // Update localStorage when language changes
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };
  
  // Translation function
  const t = (key: string, params?: Record<string, string>): string => {
    let translated = translations[language][key] || key;
    
    // Replace parameters if provided
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translated = translated.replace(`{${param}}`, value);
      });
    }
    
    return translated;
  };
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = () => useContext(LanguageContext); 